# .lintinel.yml

rules:
  YAMLLinter: false
  BashLinter: true
  TerraformModuleVersioning: false
  DockerfileBestPractices: false
  MissingDotfiles: false

ai:
  enabled: true
  provider: openai
  model: gpt-4
  tone: mentor  # or strict, friendly, playful
